name: Deploy rcpk

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.RCPK_HOST }}
          username: ${{ secrets.RCPK_USER }}
          key: ${{ secrets.RCPK_KEY }}
          script: |
            #Переключаемся в нужную папку
            cd ~/rcpk.site/public_html/wp-content/themes/rcpk
            
            #Клинируем репозиторий в папку (только для первой выгрузки!!!)
            git clone https://github.com/site100ru/rcpk.git .
            
            #Клинируем репозиторий в папку
            #git pull
            
            #Если кто то изменил файлы на сервере минуя GitHub, перезаписываем версию на сервере из GitHub
            #git reset --hard HEAD
            #git pull origin main
